/**
 * Authoritative TypeScript Types for Legal Consistency & Change Intelligence
 * Strictly implementing AI Reasoning Contract v1.2.2 and System Prompt v1.2.2.
 */

export type DocumentRelationshipStatus = 'related' | 'unrelated' | 'uncertain';

export type RelationshipTaxonomy =
  | 'modification'
  | 'addition'
  | 'removal'
  | 'apparent_conflict'
  | 'clarification'
  | 'uncertain';

export type CoexistenceValue = boolean | 'uncertain' | null;

export interface CitationRef {
  document_id: string;
  clause_id: string;
}

export interface Finding {
  finding_id: string;
  relationship: RelationshipTaxonomy;
  description: string;
  evidence: CitationRef[];
  ai_interpretation: string;
  potential_consideration: string | null;
  uncertainty: string | null;
  suggested_question: string | null;
  coexistence_possible: CoexistenceValue;
  /** Server-derived only: "full_document_search" on confirmed removals */
  removal_evidence_completeness?: 'full_document_search';
}

export interface Obligation {
  text: string;
  evidence: CitationRef[];
  /** Required key on every entry; string or null */
  deadline: string | null;
}

export interface UnresolvedReference {
  referencing_document_id: string;
  referencing_clause_id: string;
  referenced_identifier: string;
}

export interface DocumentRelationshipAssessment {
  status: DocumentRelationshipStatus;
  reasoning: string;
}

/**
 * Raw output shape generated by the model (conforming to System Prompt v1.2.2)
 */
export interface ModelRawOutput {
  schema_version: string;
  document_relationship_assessment: DocumentRelationshipAssessment;
  findings: Finding[];
  obligations: Obligation[];
  unresolved_references: UnresolvedReference[];
  overall_uncertainties: string[];
}

export interface InjectedContentFlag {
  document_id: string;
  clause_id: string;
  matched_pattern: string;
  snippet: string;
}

export interface AnalysisMetadata {
  pipeline_version: string;
  cache_hit: boolean;
  model_identifier: string;
  execution_time_ms: number;
  model_call_count: number;
}

/**
 * Validated final output emitted by the server after the Consolidated Validation Pipeline
 */
export interface ValidatedAnalysisReport {
  schema_version: '1.2';
  document_relationship_assessment: DocumentRelationshipAssessment;
  findings: Finding[];
  obligations: Obligation[];
  unresolved_references: UnresolvedReference[];
  overall_uncertainties: string[];
  disclaimer: string;
  injected_content_flags: InjectedContentFlag[];
  analysis_metadata: AnalysisMetadata;
}

/**
 * Server-held clause structure
 */
export interface ServerClause {
  id: string;
  document_id: string;
  section_reference?: string;
  text: string;
  normalized_text: string;
  defined_terms: string[];
  shingles: string[];
  orphan_confirmed?: boolean;
}

export interface ProcessedDocument {
  id: string;
  filename: string;
  hash: string;
  clauses: ServerClause[];
  raw_text: string;
}

export interface UploadedFile {
  filename: string;
  buffer: Buffer;
  mimeType: string;
  size: number;
}
